apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processing-service
  template:
    metadata:
      labels:
        app: image-processing-service
    spec:
      containers:
        - name: image-processing-container
          image: 153676591437.dkr.ecr.eu-west-2.amazonaws.com/image-processing:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: image-processing-service
spec:
  selector:
    app: image-processing-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
