storage:
  type: elasticsearch
  dependencies:
    # use a different StorageClass here if needed
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2

elasticsearch:
  enabled: true
  data:
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
      storageClassName: gp2
