apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./auth/auth-deployment.yaml
  - ./image-processing/image-processing-deployment.yaml
  - ./Frontend/react-frontend-deployment.yaml
  - ./istio/virtual-services.yaml
  - ./istio/gateway.yaml
  - ./istio/kiali-vs.yaml

